### PR TITLE
Changed test format and incorporated rebabel changes

### PR DESCRIPTION
**Pull request by ElizabethThorner**

### CODE REVIEW

**Comment by ghost** [comment]
@ElizabethThorner I ran these changes with the rebabel_import_and_export_testing.py file and didn't receive the correct output file. 

Screen Shot 2024-09-27 at 9 09 53 PM

**Comment by mr-martian** [comment]
@joembarron I see that that script was deleted in this branch - does your copy have `FlexText/en` or `FlexText:en` in the mapping parameter? (The latter is needed now)

**Comment by ElizabethThorner** [comment]
I’m not completely sure why the change happened, but the only difference was that text and the part of speech were in a different order in the flextext file, so I thought it was fine. They’re still both under the word tag, I don’t think their order in relation to each other makes a difference.

**Comment by ghost** [comment]
> @joembarron I see that that script was deleted in this branch - does your copy have `FlexText/en` or `FlexText:en` in the mapping parameter? (The latter is needed now)

@mr-martian I just changed from the forward slash to the colon in the mapping. Now I'm getting the expected output file. 

 Screen Shot 2024-09-28 at 9 16 56 AM

@ElizabethThorner I made the mapping update in the rebabel_import_and_export_testing.py file. I am going to merge the code now.

**Review by ghost — APPROVED** [review]

**Pull request merged**
